manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      revision: main
    - name: badjeff
      url-base: https://github.com/badjeff
      revision: main
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-behavior-mouse-key-toggle
      remote: badjeff
      revision: main
  self:
    path: config
